server:
  port: 20009
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      # 在gateway中配置uri配置有三种方式，包括
      # 第一种：ws(websocket)方式: uri: ws://localhost:9000
      # 第二种：http方式: uri: http://localhost:8130/
      # 第三种：lb(注册中心中服务名字)方式：uri: lb://brilliance-consumer
      routes: #配置路由路径
        - id: auth #路由的ID
          uri: lb://auth #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/auth/**
          filters:
            - StripPrefix=1 # 表示在将请求发送到下游之前从请求中剥离的路径个数
        - id: system
          uri: lb://system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9002/auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 16379
    host: 192.168.205.232
    password: eversec123!@#
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/auth/rsa/publicKey"
      - "/system/admin/login"
      - "/system/admin/register"
      - "/system/minio/upload"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info
    com.yy.gateway: debug

# LogStash访问,elk日志收集
logstash:
  host: 192.168.205.232